runtime: java11
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.9
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 70
  max_idle_instances: 1
inbound_services:
  - warmup
env_variables:
  JAVA_USER_OPTS: '-Dspring.profiles.active=prod'
